import Image from "../img/ridwan.jpg";

const USERS_DATA = {
  leaves: [
    {
      id: 1,
      staff_id: "ridwan",
      email: "balogunrdiwan@gmail.com",
      firstName: "Ridwan",
      lastName: "Balogun",
      type: "annual",
      status: "approved",
      date_requested: "31-01-2021",
      date_approved: "31-01-2021",
      days: "5",
      initial_balance: "20",
      final_balance: "15",
      leave_start: "31-01-2021",
      leave_end: "31-01-2021",
      resumption: "31-02-2021",
      dateCreated: "31-01-2021",
      line_manager: "Tunde",
    },
    {
      id: 2,
      staff_id: "tunde",
      email: "tunde@gmail.com",
      firstName: "Tunde",
      lastName: "Babatunde",
      type: "annual",
      status: "pending",
      date_requested: "04-02-2021",
      date_approved: "05-02-2021",
      days: "5",
      initial_balance: "15",
      final_balance: "10",
      leave_start: "05-02-2021",
      leave_end: "05-02-2021",
      resumption: "05-02-2021",
      dateCreated: "05-02-2021",
      line_manager: "Tope",
    },
    {
      id: 3,
      staff_id: "Joseph",
      email: "joseph@gmail.com",
      firstName: "Joseph",
      lastName: "Daniel",
      type: "sick",
      status: "pending",
      date_requested: "31-01-2021",
      date_approved: "31-01-2021",
      days: "3",
      initial_balance: "10",
      final_balance: "7",
      leave_start: "31-01-2021",
      leave_end: "31-01-2021",
      resumption: "31-02-2021",
      dateCreated: "31-01-2021",
      line_manager: "Tunde",
    },
    {
      id: 4,
      staff_id: "Jane",
      email: "jane@gmail.com",
      firstName: "Jane",
      lastName: "Cinderella",
      type: "exam",
      status: "declined",
      date_requested: "04-01-2021",
      date_approved: "31-01-2021",
      days: "5",
      initial_balance: "15",
      final_balance: "10",
      leave_start: "31-01-2021",
      leave_end: "31-01-2021",
      resumption: "31-02-2021",
      dateCreated: "31-01-2021",
      line_manager: "Tunde",
    },
  ],
  staffs: [
    {
      id: 1,
      staff_id: "ridwan",
      email: "balogunridwan@gmail.com",
      firstName: "Ridwan",
      lastName: "Balogun",
      type: "admin",
      line_manager: "balogun",
      sickLeave: 10,
      examLeave: 5,
      annualLeave: 20,
    },
    {
      id: 2,
      staff_id: "ivie",
      email: "ivie@gmail.com",
      firstName: "Ivie",
      lastName: "Princess",
      type: "staff",
      line_manager: "balogun",
      sickLeave: 10,
      examLeave: 5,
      annualLeave: 20,
    },
    {
      id: 2,
      staff_id: "ivie",
      email: "ivie@gmail.com",
      firstName: "Ivie",
      lastName: "Princess",
      type: "staff",
      line_manager: "balogun",
      sickLeave: 10,
      examLeave: 5,
      annualLeave: 20,
    },
    {
      id: 3,
      staff_id: "lizzy",
      email: "Elizabeth@gmail.com",
      firstName: "Elizabeth",
      lastName: "Chisom",
      type: "staff",
      line_manager: "balogun",
      sickLeave: 10,
      examLeave: 5,
      annualLeave: 20,
    },
    {
      id: 4,
      staff_id: "bede",
      email: "Ehiogu@gmail.com",
      firstName: "Ehiogu",
      lastName: "bede",
      type: "staff",
      line_manager: "tunde",
      sickLeave: 10,
      examLeave: 5,
      annualLeave: 20,
    },
  ],
};

export default USERS_DATA;
